The whole task was easy and I didn't got stuck 
anywhere except at the last.

I would like to call the mistake 'The Big 
Silly Error' because I thought that it was 
big(I spent 1 hour on it) but it was a very 
big silly mistake.

I wrote the test file properly and it was 
actually correct and proper but the only 
mistake I did was not to update the 
python-zulip-api repository because of which 
it was giving an error.

I have provided you with the error's 
screenshot.