I had problems running the bot, but was solved after deleting and re-cloning the repo.
I also had a problem running test on the bot, but that was solved too
by deleting test_message_info.py and re-creating it.